name: provider_arc
description: A new Flutter project.

version: 1.0.14+14

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.16.1
  cupertino_icons: ^1.0.0
  http: ^0.12.0+2
  logger: ^0.9.4
  shared_preferences: ^0.5.3+4
  provider: ^3.0.0
  url_launcher: ^5.4.2
  flutter_local_notifications: ^1.4.4+1
  firebase_auth: ^0.16.0
  cloud_firestore:
  firebase_storage:
  firebase_messaging: ^6.0.12
  rflutter_alert: ^1.0.3
  flutter_spinkit: ^4.1.2+1
  flutter_country_picker: ^0.1.4
  line_awesome_icons: ^1.0.4+2
  font_awesome_flutter: ^8.8.1
  mdi: ^0.2.1
  google_maps_flutter: ^0.5.21+7
  google_maps_webservice: ^0.0.17
  geolocator: ^5.3.1
  location: ^2.3.5
  permission_handler: ^5.0.0+hotfix.8
  #google_map_polyline: ^0.2.0+1
  flutter_polyline_points: ^0.2.4
  flutter_launcher_icons: "^0.7.3"
  badges: ^1.1.1
  dotted_border: ^1.0.5
  flutter_dash: ^0.0.1
  flare_flutter: ^2.0.3
  fluttertoast: ^4.0.0
  image_picker: ^0.6.1+3
  image_cropper: ^1.2.2
  enum_to_string: ^1.0.9
  cached_network_image: ^2.2.0+1
  flutter_webview_plugin: ^0.3.11
  shimmer: ^1.1.1
  flutter_rating_bar: ^3.0.1+1
  rating_bar: ^0.2.0
  flutter_recaptcha_v2: ^0.1.0
  kf_drawer: ^1.1.2
  sliding_up_panel: ^1.0.2
  flutter_socket_io: ^0.6.0
  lite_rolling_switch: ^0.1.1
  full_screen_image: ^1.0.2
  flutter_dropdown: ^0.0.8
  avatar_view: ^1.0.0+3
  maps_toolkit: ^1.1.0+2
  avatar_glow: ^1.2.0
#  flutter_verification_code_input:
#    git:
#      url: git://github.com/tinylife-io/flutter_verification_code_input.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/icons/icon.png
  image_path_ios: assets/icons/icon.png
  adaptive_icon_background: assets/icons/ic_background.png
  adaptive_icon_foreground: assets/icons/ic_foreground.png

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/icons/
    - assets/flare/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Medium.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
